min_version = "2025.1.14"

[tools]
rust = "1.89.0"
node = "22.12.0"
deno = "1.46.1"
cargo-binstall = "1.10.15"
"npm:lefthook" = "1.8.5"
"npm:@commitlint/config-conventional" = "19.6.0"
"npm:@commitlint/cli" = "19.6.0"
"npm:@commitlint/types" = "19.5.0"
"npm:repomix" = "1.5.0"
"cargo:https://github.com/DenisGorbachev/cargo-doc2readme" = "branch:dev"
"cargo:cargo-sort" = "1.0.9"
"cargo:cargo-hack" = "0.6.33"
"cargo:cargo-machete" = "0.7.0"
"cargo:cargo-nextest" = "0.9.102"
"cargo:cargo-expand" = "1.0.114"
"cargo:rumdl" = "0.0.166"

[tasks."build"]
run = "cargo build"

[tasks."fmt"]
run = "cargo fmt --all"

[tasks."lint"]
depends = ["lint:code", "lint:docs", "lint:deps"]

[tasks."test"]
depends = ["test:code", "test:docs"]

[tasks."lint:code"]
run = "cargo clippy --all-targets --all-features -- -D warnings"

[tasks."lint:docs"]
run = "rumdl check"

[tasks."lint:deps"]
run = "cargo machete --with-metadata"

[tasks."test:code"]
run = "cargo nextest run --all-features --no-tests warn"

[tasks."test:docs"]
run = "cargo test --doc --all-features --no-fail-fast --quiet"

[tasks."sort:deps"]
run = "cargo sort"

[tasks."check"]
run = "cargo check --all-targets --all-features"

[tasks."fix"]
depends = ["fix:code", "fix:deps"]

[tasks."fix:code"]
env = { __CARGO_FIX_YOLO = 'yeah' }
run = "cargo clippy --all-targets --all-features --fix --allow-dirty --allow-staged"

[tasks."fix:deps"]
run = "cargo machete --with-metadata --fix"

[tasks."watch"]
run = """
#!/usr/bin/env bash
set -euo pipefail
PWD=$(pwd)
CMD_RAW="nextest run $*"
CMD_NO_WHITESPACE="$(echo -e "${CMD_RAW}" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')"
cargo watch --clear --watch "$PWD" --exec "$CMD_NO_WHITESPACE" "$@"
"""

[tasks."gen:readme"]
run = "./README.ts --output README.md"

[tasks."commitlint"]
run = "commitlint --extends \"$(mise where npm:@commitlint/config-conventional)/lib/node_modules/@commitlint/config-conventional/lib/index.js\""

[tasks."repomix"]
usage = """
arg "<file>"
arg "[rest]" var=#true
"""
run = """
#!/usr/bin/env bash
set -xeuo pipefail
dir=$MISE_PROJECT_ROOT
file=$usage_file
header=$(taplo get -f "$dir/Cargo.toml" "package.description")
repomix \
    --include src,tests,examples \
    --no-file-summary \
    --no-directory-structure \
    --header-text "$header" \
    --output "$file" \
    {{arg(name="rest")}} \
    "$@" \
    $dir
"""

[tasks."agent:on:stop"]
depends = ["agent:test", "lint", "fmt", "sort:deps"]

[tasks."agent:test"]
depends = ["agent:test:code", "test:docs"]

[tasks."agent:test:code"]
# don't include `--fail-fast` because it's better to let the agent see all failures
# reduce output to save tokens
run = "mise run test:code -- --cargo-quiet --hide-progress-bar --status-level fail --final-status-level flaky"
